### ISSUE TITLE
User Flow

### ISSUE THREAD

**Issue by ijsnow** [MongooseUASoftEng/MongoosePOS#5]
Lets use this issue to discuss how we want to implement the user flow of this task. By that I mean whether we want to have a separate page for each "page" or template or do we want a modal to pop up for each "page". There are many different ways to do this. Let's discuss what we all think the option resulting in the best user experience(UX) or ease of use is. 

A couple examples that affect the UX can be number of clicks that it takes to get to a certain point or do a certain task and the amount of times a page changes to do a certain task can throw off the user's context of where they are in the app. 

We should make some wire frames(or mock ups) of the app as we go through the suggested user flows of the app. There are apps you can download to make the wire frames but [heres a website to do it with](https://moqups.com/). I've made the wire frames and then just took a picture of the so I don't have to worry about getting the membership.

**Comment by willpoorman** [comment]
I have a few thoughts on this but I'll save them until I have time to flesh them out a bit more. If you look on trello, I uploaded wireframes made by Dr. Phillips for each page. We can use that as a launching point at least.

**Comment by willpoorman** [comment]
Oops, did not know that's what close and comment meant.

**Comment by hjdarnel** [comment]
I'm fine with whatever honestly. I don't want to overcomplicate things. I think having a box pop up after searching for a product, with details and add/quantity/cancel could be cool, and then when closing that it leaves you at the product search field with transaction entries below it. If we wanted to do all modal windows, that would be fine for me too.

**Comment by willpoorman** [comment]
So here is my view of how the app should flow from page to page. It's interactive but only to the extent where it shows movement from page to page. So you can click buttons related to what we're doing this sprint but you can't change numbers or actually add things. If you guys get confused on how to use it, let me know and I'll explain and we can figure out how to make it more intuitive:
https://app.moqups.com/will.k.poorman@gmail.com/vZrNzyO05Y/view

**Comment by ijsnow** [comment]
I like that flow. I'm fine with using this user flow unless anyone else has something else to say. I agree we don't need to overcomplicate things either, Henry. I just wanted to make sure we had the same thing in mind so that we weren't making things that weren't going to fit together. I also wanted it to be in our heads that when we are working on real projects, this is an important thing to spend time on. At Atlas, I was never allowed to start coding anything until I made wire frames and had them approved for projects where I was changing anything on the front end.

**Comment by hjdarnel** [comment]
That's fine for me. What would work best for making those dropdowns, though, from the pages that we already have? And @ijsnow yeah I know the layout is important, I'm just saying that we don't need to overcomplicate the design

**Comment by natedemery** [comment]
I like Will's mockup, but I don't think the transaction total needs to be a dropdown. I think it would be more user-friendly if it were just permanently there.

**Comment by ijsnow** [comment]
@hjdarnel Ah, I see what you meant. Yea, I agree. The best designs are the simple ones. It makes for natural and intuitive user flows. 

If we want to use drop downs, we just put the templates we have in a div that we make collapsible with a little css and javascript.

**Comment by willpoorman** [comment]
@natedemery Hmm, I'm good with having them either way. With them being drop downs, i think it's pretty intuitive and it allows the user to segment what they're doing and focus on one part at a time. Especially if there's a lot of products being add, that could make the page really long and the collapsing it when moving on to the payment might be nice

**Comment by willpoorman** [comment]
I think we should definitely make sure that this UI is touch friendly as well though, I know a lot of point of sales apps are run on tablets or at least on touchscreens so it would make since to have big, easy to press buttons and easy to read text. It's not like there's a ton of information that needs to be displayed at once most of the time, so it shouldn't be too large to keep everything simple and big. Maybe clicking anywhere on the transaction total line will open/collapse the drop-down/drawer instead of just the little triangle.

**Comment by ijsnow** [comment]
We could have it default to being opened and have it there as an option to collapse it if they want.

**Comment by natedemery** [comment]
I think it works well if it's collapsible, but the default should be expanded. Think about it: when you start a transaction, you're never going to complete a transaction without adding products.

**Comment by willpoorman** [comment]
@hjdarnel I don't remember them right now, but when i find them I'll link them here but I remember there being some meteor example app that had drop-downs/drawers in them

**Comment by willpoorman** [comment]
default expanded sounds good to me

**Comment by willpoorman** [comment]
Also, how do people feel about the logo I made? I like the minimal style but scared it looks more like a cat than a mongoose on first impression.

**Comment by hjdarnel** [comment]
I figured most people don't know what a mongoose is anyway, but it looks less like a cat and more mongoose-like imo

**Comment by natedemery** [comment]
I think it's fine. Nobody knows what a mongoose looks like anyway. Haha.

**Comment by ijsnow** [comment]
If we are wanting to go as far as making it mobile friendly, we should stay away from modals(pop-ups). Mobile browsers have trouble with fixed/absolutely positioned elements overlaying things. Weird stuff starts happening like the background scrolling among other things.

I like the logo. I don't really see a cat in it.

**Comment by natedemery** [comment]
True, and the size/aspect ratio changes from device to device. Bootstrap makes it pretty easy though.

**Comment by willpoorman** [comment]
So suggestions in place of a modal for the selected product page for mobile then?

**Comment by natedemery** [comment]
I think if we optimize it for desktop/tablet, we could still use a modal. No real store would use a phone for a POS system anyway.

**Comment by ijsnow** [comment]
Weird stuff would still happen on a tablet. It's the touch screens that cause the issue. It probably won't cause too much of an issue depending on the amount of things we have in the modal. 

I think on mobile platforms, the normal thing to do when you have enough in what would be in a modal, you just go to another 'page'. We could also have it in an expanding div that comes in and is in the normal flow of the html instead of a modal popping up that is fixed and all that jazz.

**Comment by natedemery** [comment]
That's a pretty good work around.

**Comment by willpoorman** [comment]
Well we can see if the modal will have problems, we can upload it to meteor servers, then someone who has a tablet can test it. When you say expanding div do you basically mean like my drop-down in the mock up? I guess we could do a nested drop-down inside of it, though that could start to make things a little confusing or messy formatting wise

**Comment by ijsnow** [comment]
You can connect with your local host on a phone or tablet on the same network. In the URL just replace 'localhost' with your IP address which you can find from a command that I forget from the command prompt. The weird stuff will definitely still happen on a tablet. I just don't know if it'll be that much of an issue. If we have a list in there or something that causes the modal to go off the screen at all we shouldn't use it. 

And yea I do. In my head I don't really think of that as a drop down though.

**Comment by willpoorman** [comment]
Okay, well I say we try the modal first. the modal will basically contain what is on the selected product page now, plus a number input and an add and cancel button so I don't think it will take up much room. We could even put all the product info in a scrolling text box in the modal so that we make sure it doesn't get too long and go off the page of a smaller display.

Do we have a way of checking whether it is on a mobile device/tablet via javascript or Meteor? If so, we could have a modal for computers and maybe jump to another page or have the expanding div for mobile/tablet

**Comment by ijsnow** [comment]
Scrollable elements within modals make the problem it even worse lol. We are getting into the real fun(aggravating) part of web development here. 

There are unreliable ways to check for type of browser with javascript. This is something that I tried when working on a fix for this at Atlas but quickly found that this was a [bad idea](https://css-tricks.com/browser-detection-is-bad/). The "web standards" say that websites should be cross browser compatible so that anyone on any browser can use every feature in the site and design for sites should be a [mobile first design](http://www.webinsation.com/why-should-i-design-for-mobile-first/). That causes some pains because each browser is implemented differently and some are better than others. Because checking browser types is unreliable its not really cross browser compatible.

By the way, I don't care if we want go as far as making it touch friendly or use a collapsing div or not, I'm just making sure we follow best practices and want to point out things that I've encountered before/seen or read about that cause issues.

**Comment by willpoorman** [comment]
I'm glad we're taking the time to talk it so we all understand these things. It sucks though, that mobile kinda makes a lot of neat and useful website features unusable. 

I don't really like the idea of taking the user away from the  transaction page to add the product to the transaction, that sounds like it would make it less intuitive. But adding nested expanding divs/drop-downs seems like it could clutter up things as well. So I'm not too in favor of adding another expanding div inside the added product one. If you can make a mock up of how you think it should be and it still looks nice and not confusing, we can go with that. I can make the moqup that I linked to so that you can edit it if you want, or you can make your own.

Also, I think it's pretty funny how in the mobile first link, it says "Look at the difference between these two pictures...insert mobile image here" and there are no pictures.

**Comment by ijsnow** [comment]
Adding an expanding div would be the same thing as adding a modal except
it's baked into the normal flow of the elements on the page. I'm not sure
that it would clutter things up much more than a modal.

Lol I didn't even notice that. That's funny

**Comment by aepohl** [comment]
Do we really need to make it mobile friendly though?  If it's purpose is to be an in-store POS system, then in what scenario would you need to access it from a mobile device?

**Comment by willpoorman** [comment]
Many POS systems are run on tablets or at least touchscreens. That's why I think it's kind of important.

**Comment by willpoorman** [comment]
A lot of POS systems are on tablets or at least touchscreens, that's why i think it's important. 

Okay, so if you guys look at the moqup now, it goes from landing page to transaction page with transaction total expanded by default. There are now 2 search buttons, one does a modal, one does an expanding div. The div makes sense now that I've worked out how it would actually work. I'm fine with either. What are everyone else's opinions?

My only thought against the expanding div at this point is that the 2 main reasons I liked the modal were 1. It didn't take the user to a new page, and 2. it acted as a dialog box that needed the user to do something, either add, or cancel before they can do anything else. With the expanding div, it allows the user to do other things and ignore it/forget about it it.

**Comment by willpoorman** [comment]
Okay guys lets see if we can close this issue today. Thoughts on my last comment and the updated moqup?

**Comment by ijsnow** [comment]
Yea I agree with your points. My only comment on that would be is this something that would cause that big of an issue if the user was looking around at other things on the page instead of adding the product? If their goal was to add the product would they do you think they would get distracted and go mess with other things instead of adding it?

These are tough questions to answer because you don't want to assume anything about the user because people can be dumb and unpredictable. Again, I'm not sure if the issues with modals would be that big of an issue with the amount of content we are putting into them.

**Comment by willpoorman** [comment]
My thought of where it could go wrong is:
Say they're adding a product to the list of products to be bought, but forget to hit add because the customer asks a question or something. They move on to adding the payment and commit the purchase but since they never hit add, the purchase is committed but one of the products is missing.

My thought on fixing it if we use the div is to make it so if they commit the purchase, i.e. hit the "Complete Transaction" button, it will give them an alert or something saying that they can't complete it until the add or cancel button has been hit

**Comment by willpoorman** [comment]
Alright, since there has been no dissenting opinions. I am going to close this issue.
We have decided to:
- Use the expanding div version of our mock up, found here: https://app.moqups.com/will.k.poorman@gmail.com/vZrNzyO05Y/view
- When we get to implementing the Submit/Complete Transaction/Commit Purchase/whatever we call it button. we will disallow the submission until the selected product div is closed by hitting either "add" or "cancel"
